site_name: MIL
repo_url: https://github.com/hmyuuu/MIL-zh-demo
repo_name: MIL-zh-demo
docs_dir: "./src"

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: zh
  - autorefs
  - minify:
      minify_html: true
      docs_structure: folder
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
        - locale: zh
          name: 中文
          default: true
          build: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: friendly
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - assets/css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

extra:
  version:
    provider: mike
    default: latest
    alias: true

nav:
  - 目录: ./en/index.md
  - Introduction: ./en/C01_Introduction.md
  - Basics: ./en/C02_Basics.md
  - Logic: ./en/C03_Logic.md
  - Sets and Functions: ./en/C04_Sets_and_Functions.md
  - Elementary Number Theory: ./en/C05_Elementary_Number_Theory.md
